# Generated by Django 5.2.12 on 2026-04-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="products.tag",
                verbose_name="Tags",
            ),
        ),
    ]
