# Generated by Django 5.2.12 on 2026-04-05 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_review_rating_alter_review_title_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wishlist",
            options={"ordering": ["-created_at"]},
        ),
    ]
