# Generated by Django 5.2.12 on 2026-04-12 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recentlyviewed",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="viewed_by",
                to="products.product",
            ),
        ),
    ]
