# Generated by Django 5.2.12 on 2026-04-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_recentlyviewed_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="barcode",
            field=models.CharField(
                blank=True,
                help_text="Product barcode (EAN-13, UPC-A, etc.)",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Barcode",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="labels",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of labels: new, bestseller, discounted, limited, preorder",
                verbose_name="Product Labels",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="qr_code",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/qrcodes/",
                verbose_name="QR Code",
            ),
        ),
    ]
