# Generated by Django 5.2.12 on 2026-05-06 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_product_barcode_product_labels_product_qr_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
    ]
