# Generated by Django 5.2.12 on 2026-08-03 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_remove_product_stock"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Review",
        ),
    ]
