# Generated by Django 5.2.12 on 2026-03-12 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g., Home, Work, etc.",
                        max_length=255,
                        verbose_name="Address Title",
                    ),
                ),
                ("province", models.CharField(max_length=255, verbose_name="Province")),
                ("city", models.CharField(max_length=255, verbose_name="City")),
                ("street", models.CharField(max_length=255, verbose_name="Street")),
                (
                    "alley",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Alley"
                    ),
                ),
                (
                    "building_number",
                    models.CharField(
                        max_length=20, verbose_name="Building/Plate Number"
                    ),
                ),
                (
                    "floor",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Floor"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Unit"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=20, verbose_name="Postal Code"),
                ),
                (
                    "receiver_name",
                    models.CharField(max_length=255, verbose_name="Receiver Name"),
                ),
                (
                    "receiver_phone",
                    models.CharField(max_length=11, verbose_name="Receiver Phone"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Default Address"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
    ]
