# Generated by Django 5.2.12 on 2026-03-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(max_length=10, verbose_name="Postal Code"),
        ),
    ]
