# Generated by Django 5.2.12 on 2026-03-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_address_postal_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=11, verbose_name="Phone Number")),
                (
                    "code",
                    models.CharField(max_length=6, verbose_name="Verification Code"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                ("is_used", models.BooleanField(default=False, verbose_name="Is Used")),
            ],
            options={
                "verbose_name": "OTP",
                "verbose_name_plural": "OTPs",
                "indexes": [
                    models.Index(
                        fields=["phone", "created_at"],
                        name="accounts_ot_phone_463bcb_idx",
                    )
                ],
            },
        ),
    ]
