# Generated by Django 5.2.12 on 2026-03-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="phone",
            field=models.CharField(max_length=15, verbose_name="Phone Number"),
        ),
    ]
