# Generated by Django 5.2.12 on 2026-03-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_otp_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=15, unique=True, verbose_name="Phone Number"
            ),
        ),
    ]
