# Generated by Django 5.2.12 on 2026-03-14 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_user_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "store_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Store Name"
                    ),
                ),
                (
                    "store_slug",
                    models.SlugField(
                        max_length=120, unique=True, verbose_name="Store Slug"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="sellers/logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="sellers/banners/",
                        verbose_name="Banner",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Store Description"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Temporarily Suspended"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verified At"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Rejection Reason"),
                ),
                (
                    "business_phone",
                    models.CharField(max_length=15, verbose_name="Business Phone"),
                ),
                (
                    "business_email",
                    models.EmailField(max_length=254, verbose_name="Business Email"),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "bank_info",
                    models.JSONField(
                        default=dict,
                        help_text="Store bank account details as JSON",
                        verbose_name="Bank Information",
                    ),
                ),
                (
                    "documents",
                    models.JSONField(
                        default=list,
                        help_text="List of uploaded document paths",
                        verbose_name="Documents",
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Percentage taken by platform",
                        max_digits=5,
                        verbose_name="Commission Rate (%)",
                    ),
                ),
                (
                    "total_sales",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Total Sales",
                    ),
                ),
                (
                    "total_orders",
                    models.PositiveIntegerField(default=0, verbose_name="Total Orders"),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Current Balance",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Applied At"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_sellers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seller",
                "verbose_name_plural": "Sellers",
                "indexes": [
                    models.Index(
                        fields=["status"], name="accounts_se_status_5844c2_idx"
                    ),
                    models.Index(
                        fields=["store_slug"], name="accounts_se_store_s_b1b1f3_idx"
                    ),
                    models.Index(
                        fields=["-total_sales"], name="accounts_se_total_s_7bcbb3_idx"
                    ),
                ],
            },
        ),
    ]
