# Generated by Django 5.2.12 on 2026-03-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_seller"),
        ("rbac", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                through="rbac.UserRole",
                through_fields=("user", "role"),
                to="rbac.role",
                verbose_name="Roles",
            ),
        ),
    ]
