# Generated by Django 5.2.12 on 2026-08-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_user_email_verified_user_email_verified_at"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="otp",
            name="accounts_ot_phone_463bcb_idx",
        ),
        migrations.AddField(
            model_name="otp",
            name="email",
            field=models.EmailField(
                db_index=True,
                default="legacy-otp@mallbyte.local",
                max_length=254,
                verbose_name="Email Address",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="otp",
            name="phone",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Phone Number"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                unique=True,
                verbose_name="Phone Number",
            ),
        ),
        migrations.AddIndex(
            model_name="otp",
            index=models.Index(
                fields=["email", "created_at"], name="accounts_ot_email_4c9cd8_idx"
            ),
        ),
    ]
