# Generated by Django 5.2.12 on 2026-08-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_remove_otp_accounts_ot_phone_463bcb_idx_otp_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(max_length=20, verbose_name="Postal Code"),
        ),
        migrations.AlterField(
            model_name="address",
            name="receiver_phone",
            field=models.CharField(max_length=20, verbose_name="Receiver Phone"),
        ),
    ]
