# Generated by Django 5.2.12 on 2026-07-05 14:26

import apps.returns.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "request_number",
                    models.CharField(
                        db_index=True, editable=False, max_length=32, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("waiting_for_item", "Waiting for returned item"),
                            ("item_received", "Item received"),
                            ("inspecting", "Inspecting"),
                            ("refund_pending", "Refund pending"),
                            ("refunded", "Refunded"),
                            ("replaced", "Replaced"),
                            ("cancelled", "Cancelled"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="submitted",
                        max_length=32,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("damaged", "Damaged item"),
                            ("wrong_item", "Wrong item"),
                            ("defective", "Defective"),
                            ("not_as_described", "Not as described"),
                            ("size_or_fit", "Size or fit issue"),
                            ("changed_mind", "Changed mind"),
                            ("late_delivery", "Late delivery"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                (
                    "requested_resolution",
                    models.CharField(
                        choices=[
                            ("refund", "Refund"),
                            ("replacement", "Replacement"),
                            ("store_credit", "Store credit"),
                            ("repair", "Repair"),
                            ("other", "Other"),
                        ],
                        default="refund",
                        max_length=32,
                    ),
                ),
                (
                    "refund_method",
                    models.CharField(
                        choices=[
                            ("original_payment", "Original payment method"),
                            ("store_credit", "Store credit"),
                            ("manual", "Manual refund"),
                            ("none", "No refund"),
                        ],
                        default="original_payment",
                        max_length=32,
                    ),
                ),
                ("customer_note", models.TextField(blank=True)),
                ("internal_note", models.TextField(blank=True)),
                (
                    "total_requested_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_approved_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="return_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_requests",
                        to="orders.order",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_return_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReturnItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("damaged", "Damaged item"),
                            ("wrong_item", "Wrong item"),
                            ("defective", "Defective"),
                            ("not_as_described", "Not as described"),
                            ("size_or_fit", "Size or fit issue"),
                            ("changed_mind", "Changed mind"),
                            ("late_delivery", "Late delivery"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("opened", "Opened"),
                            ("used", "Used"),
                            ("damaged", "Damaged"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("received", "Received"),
                            ("accepted", "Accepted"),
                            ("refunded", "Refunded"),
                            ("replaced", "Replaced"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=32,
                    ),
                ),
                ("customer_note", models.TextField(blank=True)),
                ("inspection_note", models.TextField(blank=True)),
                (
                    "requested_refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "approved_refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_items",
                        to="orders.orderitem",
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="returns.returnrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ReturnAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("product_photo", "Product photo"),
                            ("damage_photo", "Damage photo"),
                            ("receipt", "Receipt"),
                            ("shipping_label", "Shipping label"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.returns.models.return_file_upload_path
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="return_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "return_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="returns.returnitem",
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="returns.returnrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReturnShipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("carrier", models.CharField(blank=True, max_length=100)),
                (
                    "tracking_number",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("tracking_url", models.URLField(blank=True)),
                (
                    "shipping_label",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.returns.models.return_file_upload_path,
                    ),
                ),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "return_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment",
                        to="returns.returnrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReturnStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("old_status", models.CharField(blank=True, max_length=32)),
                ("new_status", models.CharField(max_length=32)),
                ("note", models.TextField(blank=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="return_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="returns.returnrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(
                fields=["status", "-created_at"], name="return_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(
                fields=["customer", "-created_at"], name="return_customer_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(fields=["order"], name="return_order_idx"),
        ),
        migrations.AddConstraint(
            model_name="returnrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_requested_amount__gte", 0)),
                name="return_total_requested_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="returnrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_approved_amount__gte", 0)),
                name="return_total_approved_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="returnitem",
            constraint=models.UniqueConstraint(
                fields=("return_request", "order_item"),
                name="unique_order_item_per_return_request",
            ),
        ),
        migrations.AddConstraint(
            model_name="returnitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="return_item_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="returnitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("requested_refund_amount__gte", 0)),
                name="return_item_requested_refund_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="returnitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("approved_refund_amount__gte", 0)),
                name="return_item_approved_refund_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="returnstatushistory",
            index=models.Index(
                fields=["return_request", "-created_at"],
                name="return_history_request_idx",
            ),
        ),
    ]
