# Generated by Django 5.2.12 on 2026-08-04 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("danger", "Danger"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=20,
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("home", "Home"),
                            ("product", "Product"),
                            ("checkout", "Checkout"),
                            ("account", "Account"),
                        ],
                        db_index=True,
                        default="global",
                        max_length=30,
                    ),
                ),
                ("link_text", models.CharField(blank=True, max_length=100)),
                ("link_url", models.CharField(blank=True, max_length=500)),
                ("is_dismissible", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Announcement",
                "verbose_name_plural": "Announcements",
                "ordering": ["order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "placement"],
                        name="content_ann_status_5a5d70_idx",
                    ),
                    models.Index(
                        fields=["level", "status"], name="content_ann_level_471424_idx"
                    ),
                    models.Index(
                        fields=["starts_at", "ends_at"],
                        name="content_ann_starts__08d9b1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.TextField(blank=True)),
                ("image", models.ImageField(upload_to="content/banners/")),
                (
                    "mobile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="content/banners/mobile/"
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("home_hero", "Home Hero"),
                            ("home_top", "Home Top"),
                            ("home_middle", "Home Middle"),
                            ("category_top", "Category Top"),
                            ("product_detail", "Product Detail"),
                            ("checkout", "Checkout"),
                            ("global", "Global"),
                        ],
                        db_index=True,
                        default="home_hero",
                        max_length=40,
                    ),
                ),
                ("cta_text", models.CharField(blank=True, max_length=100)),
                ("link_url", models.CharField(blank=True, max_length=500)),
                (
                    "background_color",
                    models.CharField(
                        blank=True,
                        help_text="Optional UI color, for example: #000000",
                        max_length=20,
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        blank=True,
                        help_text="Optional UI color, for example: #FFFFFF",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_clickable", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Banner",
                "verbose_name_plural": "Banners",
                "ordering": ["placement", "order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["placement", "status"],
                        name="content_ban_placeme_50dc03_idx",
                    ),
                    models.Index(fields=["order"], name="content_ban_order_3e297b_idx"),
                    models.Index(
                        fields=["starts_at", "ends_at"],
                        name="content_ban_starts__484de8_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FAQCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "FAQ Category",
                "verbose_name_plural": "FAQ Categories",
                "ordering": ["order", "name"],
                "indexes": [
                    models.Index(fields=["slug"], name="content_faq_slug_5ca6ff_idx"),
                    models.Index(
                        fields=["is_active", "order"],
                        name="content_faq_is_acti_44a9b8_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContentPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True, max_length=500)),
                ("meta_keywords", models.CharField(blank=True, max_length=500)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("about", "About"),
                            ("terms", "Terms"),
                            ("privacy", "Privacy"),
                            ("help", "Help"),
                            ("landing", "Landing"),
                            ("custom", "Custom"),
                        ],
                        db_index=True,
                        default="custom",
                        max_length=30,
                    ),
                ),
                ("excerpt", models.TextField(blank=True)),
                ("content", models.TextField()),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_content_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_content_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Page",
                "verbose_name_plural": "Content Pages",
                "ordering": ["order", "title"],
                "indexes": [
                    models.Index(fields=["slug"], name="content_con_slug_06b9a6_idx"),
                    models.Index(
                        fields=["status", "page_type"],
                        name="content_con_status_435103_idx",
                    ),
                    models.Index(
                        fields=["is_featured", "status"],
                        name="content_con_is_feat_9ee2c2_idx",
                    ),
                    models.Index(
                        fields=["published_at"], name="content_con_publish_62c17c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FAQItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="content.faqcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ Item",
                "verbose_name_plural": "FAQ Items",
                "ordering": ["category__order", "order", "question"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="content_faq_categor_0053f9_idx",
                    ),
                    models.Index(
                        fields=["is_featured", "is_active"],
                        name="content_faq_is_feat_5114ee_idx",
                    ),
                    models.Index(fields=["order"], name="content_faq_order_626cf3_idx"),
                ],
            },
        ),
    ]
