# Generated by Django 5.2.12 on 2026-08-04 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavigationMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("header", "Header"),
                            ("footer", "Footer"),
                            ("mobile", "Mobile"),
                            ("help", "Help"),
                            ("account", "Account"),
                        ],
                        db_index=True,
                        default="header",
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Navigation Menu",
                "verbose_name_plural": "Navigation Menus",
                "ordering": ["placement", "order", "name"],
                "indexes": [
                    models.Index(fields=["slug"], name="content_nav_slug_e4c949_idx"),
                    models.Index(
                        fields=["placement", "is_active"],
                        name="content_nav_placeme_62b271_idx",
                    ),
                    models.Index(fields=["order"], name="content_nav_order_a1f3b7_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="NavigationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=120)),
                ("link_url", models.CharField(blank=True, max_length=500)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Optional icon name for frontend.",
                        max_length=80,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("requires_auth", models.BooleanField(default=False)),
                ("open_in_new_tab", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="navigation_items",
                        to="content.contentpage",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="content.navigationitem",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="content.navigationmenu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Navigation Item",
                "verbose_name_plural": "Navigation Items",
                "ordering": ["menu__order", "parent__id", "order", "label"],
                "indexes": [
                    models.Index(
                        fields=["menu", "is_active"],
                        name="content_nav_menu_id_477d71_idx",
                    ),
                    models.Index(
                        fields=["parent", "order"],
                        name="content_nav_parent__e73986_idx",
                    ),
                    models.Index(
                        fields=["page"], name="content_nav_page_id_73805a_idx"
                    ),
                    models.Index(fields=["order"], name="content_nav_order_f78308_idx"),
                ],
            },
        ),
    ]
