# Generated by Django 5.2.12 on 2026-08-05 02:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CeleryTaskLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("task_name", models.CharField(db_index=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("retry", "Retry"),
                            ("revoked", "Revoked"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=30,
                    ),
                ),
                ("queue", models.CharField(blank=True, max_length=120)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("result_summary", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("traceback", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Celery Task Log",
                "verbose_name_plural": "Celery Task Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["task_name", "-created_at"],
                        name="observabili_task_na_f4f558_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="observabili_status_80e759_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "request_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("method", models.CharField(db_index=True, max_length=10)),
                ("path", models.CharField(db_index=True, max_length=500)),
                ("query_string", models.TextField(blank=True)),
                ("status_code", models.PositiveSmallIntegerField(db_index=True)),
                ("duration_ms", models.PositiveIntegerField(db_index=True, default=0)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "response_size_bytes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="request_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Request Log",
                "verbose_name_plural": "Request Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="error",
                        max_length=20,
                    ),
                ),
                ("exception_type", models.CharField(db_index=True, max_length=255)),
                ("message", models.TextField()),
                ("traceback", models.TextField(blank=True)),
                ("method", models.CharField(blank=True, max_length=10)),
                ("path", models.CharField(blank=True, db_index=True, max_length=500)),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(db_index=True, default=500),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "fingerprint",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Used to group similar errors.",
                        max_length=255,
                    ),
                ),
                ("is_resolved", models.BooleanField(db_index=True, default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_error_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="error_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="error_logs",
                        to="observability.requestlog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Error Log",
                "verbose_name_plural": "Error Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemHealthSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("degraded", "Degraded"),
                            ("unhealthy", "Unhealthy"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("hostname", models.CharField(blank=True, max_length=255)),
                ("os_name", models.CharField(blank=True, max_length=255)),
                ("kernel_version", models.CharField(blank=True, max_length=255)),
                ("uptime_seconds", models.PositiveBigIntegerField(default=0)),
                (
                    "load_average_1m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "load_average_5m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "load_average_15m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "cpu_percent",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "memory_percent",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "disk_percent",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("process_count", models.PositiveIntegerField(default=0)),
                (
                    "database_status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("degraded", "Degraded"),
                            ("unhealthy", "Unhealthy"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "database_latency_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "redis_status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("degraded", "Degraded"),
                            ("unhealthy", "Unhealthy"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "redis_latency_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "celery_status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("degraded", "Degraded"),
                            ("unhealthy", "Unhealthy"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "celery_beat_status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("degraded", "Degraded"),
                            ("unhealthy", "Unhealthy"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "System Health Snapshot",
                "verbose_name_plural": "System Health Snapshots",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="observabili_status_5c281a_idx",
                    ),
                    models.Index(
                        fields=["cpu_percent", "-created_at"],
                        name="observabili_cpu_per_1909e5_idx",
                    ),
                    models.Index(
                        fields=["memory_percent", "-created_at"],
                        name="observabili_memory__32a9d5_idx",
                    ),
                    models.Index(
                        fields=["disk_percent", "-created_at"],
                        name="observabili_disk_pe_edb2bf_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("export", "Export"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("assign", "Assign"),
                            ("system", "System"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "object_type",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                (
                    "object_id",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["actor", "-created_at"],
                        name="observabili_actor_i_c7361b_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="observabili_action_7fb9e4_idx",
                    ),
                    models.Index(
                        fields=["object_type", "object_id"],
                        name="observabili_object__10aec8_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ObservabilityAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("database", "Database"),
                            ("redis", "Redis"),
                            ("celery", "Celery"),
                            ("celery_beat", "Celery Beat"),
                            ("error_spike", "Error Spike"),
                            ("slow_request", "Slow Request"),
                            ("disk_usage", "Disk Usage"),
                            ("memory_usage", "Memory Usage"),
                            ("cpu_usage", "CPU Usage"),
                            ("scheduled_report", "Scheduled Report"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="warning",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Example: linux, redis, celery, django",
                        max_length=120,
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Used to avoid duplicate open alerts.",
                        max_length=255,
                    ),
                ),
                ("related_object_type", models.CharField(blank=True, max_length=120)),
                ("related_object_id", models.CharField(blank=True, max_length=120)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_observability_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_observability_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Observability Alert",
                "verbose_name_plural": "Observability Alerts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "severity"],
                        name="observabili_status_984384_idx",
                    ),
                    models.Index(
                        fields=["alert_type", "-created_at"],
                        name="observabili_alert_t_8b1aef_idx",
                    ),
                    models.Index(
                        fields=["fingerprint", "status"],
                        name="observabili_fingerp_688dac_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="requestlog",
            index=models.Index(
                fields=["path", "status_code"], name="observabili_path_6ce3c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="requestlog",
            index=models.Index(
                fields=["status_code", "-created_at"],
                name="observabili_status__2bc786_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="requestlog",
            index=models.Index(
                fields=["duration_ms", "-created_at"],
                name="observabili_duratio_7d98fd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="requestlog",
            index=models.Index(
                fields=["user", "-created_at"], name="observabili_user_id_378539_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="errorlog",
            index=models.Index(
                fields=["severity", "-created_at"],
                name="observabili_severit_2b0a75_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="errorlog",
            index=models.Index(
                fields=["exception_type", "-created_at"],
                name="observabili_excepti_ff871c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="errorlog",
            index=models.Index(
                fields=["path", "-created_at"], name="observabili_path_569eab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="errorlog",
            index=models.Index(
                fields=["is_resolved", "-created_at"],
                name="observabili_is_reso_a538d0_idx",
            ),
        ),
    ]
