# Generated by Django 5.2.12 on 2026-07-02 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0009_remove_product_stock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed_amount", "Fixed Amount"),
                        ],
                        default="percentage",
                        max_length=30,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="Percentage value or fixed amount depending on discount type.",
                        max_digits=12,
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="Only useful for percentage discounts.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "usage_limit_total",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum total usage. Empty means unlimited.",
                        null=True,
                    ),
                ),
                (
                    "usage_limit_per_user",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum usage per user. Empty means unlimited.",
                        null=True,
                    ),
                ),
                ("used_count", models.PositiveIntegerField(default=0)),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicable_categories",
                    models.ManyToManyField(
                        blank=True, related_name="discounts", to="products.category"
                    ),
                ),
                (
                    "applicable_products",
                    models.ManyToManyField(
                        blank=True, related_name="discounts", to="products.product"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_discounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Discount",
                "verbose_name_plural": "Discounts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiscountUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_snapshot", models.CharField(max_length=50)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "discount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usages",
                        to="discounts.discount",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discount_usage",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discount_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Discount Usage",
                "verbose_name_plural": "Discount Usages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="discount",
            index=models.Index(fields=["code"], name="discounts_d_code_3a970a_idx"),
        ),
        migrations.AddIndex(
            model_name="discount",
            index=models.Index(
                fields=["is_active"], name="discounts_d_is_acti_ae32b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discount",
            index=models.Index(
                fields=["start_at", "end_at"], name="discounts_d_start_a_f3ecf0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discount",
            index=models.Index(
                fields=["-created_at"], name="discounts_d_created_7af897_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="discount",
            constraint=models.CheckConstraint(
                condition=models.Q(("value__gte", 0)),
                name="discount_value_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="discount",
            constraint=models.CheckConstraint(
                condition=models.Q(("min_order_amount__gte", 0)),
                name="discount_min_order_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="discount",
            constraint=models.CheckConstraint(
                condition=models.Q(("used_count__gte", 0)),
                name="discount_used_count_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="discountusage",
            index=models.Index(
                fields=["code_snapshot"], name="discounts_d_code_sn_fa6f75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discountusage",
            index=models.Index(
                fields=["user", "-created_at"], name="discounts_d_user_id_046be0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discountusage",
            index=models.Index(
                fields=["discount", "-created_at"],
                name="discounts_d_discoun_25a5bd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="discountusage",
            index=models.Index(
                fields=["-created_at"], name="discounts_d_created_0516e6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="discountusage",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_amount__gte", 0)),
                name="discount_usage_amount_non_negative",
            ),
        ),
    ]
