# Generated by Django 5.2.12 on 2026-05-05 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("products", "0008_product_barcode_product_labels_product_qr_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stock",
            options={
                "ordering": ["product__name", "warehouse__name"],
                "verbose_name": "Stock",
                "verbose_name_plural": "Stock Items",
            },
        ),
        migrations.AlterUniqueTogether(
            name="stock",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="stock",
            name="bin_code",
            field=models.CharField(blank=True, max_length=20, verbose_name="Bin Code"),
        ),
        migrations.AlterField(
            model_name="stock",
            name="reserved_quantity",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Quantity reserved for pending orders.",
                verbose_name="Reserved Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_updates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="after_quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="After Quantity"),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="before_quantity",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Before Quantity"
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_movements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("purchase", "Purchase Order"),
                    ("sale", "Customer Order"),
                    ("return", "Customer Return"),
                    ("transfer_in", "Transfer In"),
                    ("transfer_out", "Transfer Out"),
                    ("adjustment", "Stock Adjustment"),
                    ("damaged", "Damaged Goods"),
                ],
                max_length=20,
                verbose_name="Movement Type",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_movements",
                to="products.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="quantity",
            field=models.IntegerField(
                help_text="Positive = stock in, negative = stock out.",
                verbose_name="Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="reason",
            field=models.TextField(blank=True, verbose_name="Reason"),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="reference_id",
            field=models.CharField(
                blank=True,
                help_text="Order ID, Transfer ID, Purchase ID, etc.",
                max_length=100,
                verbose_name="Reference ID",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_movements",
                to="inventory.warehouse",
                verbose_name="Warehouse",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransfer",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_transfers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved By",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransfer",
            name="delivered_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Delivered At"
            ),
        ),
        migrations.AlterField(
            model_name="stocktransfer",
            name="from_warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers_out",
                to="inventory.warehouse",
                verbose_name="From Warehouse",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransfer",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_transfers",
                to="products.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransfer",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="Quantity"),
        ),
        migrations.AlterField(
            model_name="stocktransfer",
            name="reason",
            field=models.TextField(blank=True, verbose_name="Reason"),
        ),
        migrations.AlterField(
            model_name="stocktransfer",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfer_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Requested By",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransfer",
            name="shipped_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Shipped At"
            ),
        ),
        migrations.AlterField(
            model_name="stocktransfer",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_transit", "In Transit"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransfer",
            name="to_warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers_in",
                to="inventory.warehouse",
                verbose_name="To Warehouse",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransfer",
            name="tracking_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Tracking Number"
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_warehouses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="type",
            field=models.CharField(
                choices=[
                    ("main", "Main Warehouse"),
                    ("branch", "Branch Warehouse"),
                    ("third_party", "Third Party Warehouse"),
                ],
                default="branch",
                max_length=20,
                verbose_name="Warehouse Type",
            ),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["product", "warehouse"], name="inventory_s_product_112b63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["warehouse"], name="inventory_s_warehou_ecb923_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["quantity"], name="inventory_s_quantit_287c3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["last_updated"], name="inventory_s_last_up_75ebfc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["product", "warehouse"], name="inventory_s_product_5d230d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["movement_type"], name="inventory_s_movemen_018f99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["reference_id"], name="inventory_s_referen_bb4dbe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["-created_at"], name="inventory_s_created_2ec5f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(
                fields=["product"], name="inventory_s_product_5b102b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(
                fields=["from_warehouse", "to_warehouse"],
                name="inventory_s_from_wa_fc172e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(fields=["status"], name="inventory_s_status_8e22d4_idx"),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(
                fields=["-created_at"], name="inventory_s_created_c8896c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(fields=["code"], name="inventory_w_code_2cdc02_idx"),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(
                fields=["is_active"], name="inventory_w_is_acti_3ddeac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(fields=["city"], name="inventory_w_city_950b2f_idx"),
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.UniqueConstraint(
                fields=("product", "warehouse"),
                name="unique_stock_per_product_warehouse",
            ),
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)),
                name="stock_quantity_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_quantity__gte", 0)),
                name="stock_reserved_quantity_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_quantity__lte", models.F("quantity"))),
                name="stock_reserved_lte_quantity",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity", 0), _negated=True),
                name="stock_movement_quantity_not_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktransfer",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="stock_transfer_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktransfer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("from_warehouse", models.F("to_warehouse")), _negated=True
                ),
                name="stock_transfer_different_warehouses",
            ),
        ),
        migrations.RemoveField(
            model_name="stock",
            name="bin",
        ),
    ]
