# Generated by Django 5.2.12 on 2026-09-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_stock_options_alter_stock_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransfer",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approved At"
            ),
        ),
        migrations.AlterField(
            model_name="stocktransfer",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("in_transit", "In Transit"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
