# Generated by Django 5.2.12 on 2026-09-22 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_stocktransfer_approved_at_alter_stocktransfer_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="stocktransfer",
            old_name="delivered_at",
            new_name="received_at",
        ),
        migrations.AlterField(
            model_name="stocktransfer",
            name="received_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Received At",
            ),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_stock_transfers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Received By",
            ),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="shipped_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipped_stock_transfers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Shipped By",
            ),
        ),
        migrations.CreateModel(
            name="WarehouseMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_warehouse_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned By",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="inventory.warehouse",
                        verbose_name="Warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Warehouse Membership",
                "verbose_name_plural": "Warehouse Memberships",
                "ordering": ["warehouse__name", "user__email"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "warehouse"),
                        name="unique_user_warehouse_membership",
                    )
                ],
            },
        ),
    ]
