# Generated by Django 5.2.12 on 2026-08-04 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Optional UI color, for example: #FFAA00",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Support Tag",
                "verbose_name_plural": "Support Tags",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="supportticket",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tickets", to="support.supporttag"
            ),
        ),
        migrations.CreateModel(
            name="TicketAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="support/attachments/")),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="support.ticketmessage",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="support.supportticket",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Attachment",
                "verbose_name_plural": "Ticket Attachments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["ticket", "-created_at"],
                        name="support_tic_ticket__93d61e_idx",
                    ),
                    models.Index(
                        fields=["uploaded_by", "-created_at"],
                        name="support_tic_uploade_ddd966_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TicketAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("replied", "Replied"),
                            ("internal_note_created", "Internal Note Created"),
                            ("assigned", "Assigned"),
                            ("status_changed", "Status Changed"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                            ("reopened", "Reopened"),
                            ("attachment_added", "Attachment Added"),
                            ("tag_added", "Tag Added"),
                            ("tag_removed", "Tag Removed"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="support.supportticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Audit Log",
                "verbose_name_plural": "Ticket Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["ticket", "-created_at"],
                        name="support_tic_ticket__f9ed21_idx",
                    ),
                    models.Index(
                        fields=["actor", "-created_at"],
                        name="support_tic_actor_i_d89798_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="support_tic_action_04b1b6_idx",
                    ),
                ],
            },
        ),
    ]
