# Generated by Django 5.2.12 on 2026-06-03 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shipment_number",
                    models.CharField(editable=False, max_length=40, unique=True),
                ),
                (
                    "carrier",
                    models.CharField(
                        choices=[
                            ("post", "Post"),
                            ("dhl", "DHL"),
                            ("tipax", "Tipax"),
                            ("snapbox", "Snapbox"),
                            ("other", "Other"),
                        ],
                        default="post",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ready_to_ship", "Ready To Ship"),
                            ("shipped", "Shipped"),
                            ("in_transit", "In Transit"),
                            ("out_for_delivery", "Out For Delivery"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("returned", "Returned"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("tracking_number", models.CharField(blank=True, max_length=120)),
                ("tracking_url", models.URLField(blank=True)),
                (
                    "shipping_cost",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                ("receiver_name", models.CharField(max_length=120)),
                ("receiver_phone", models.CharField(max_length=20)),
                ("province", models.CharField(max_length=80)),
                ("city", models.CharField(max_length=80)),
                ("address", models.TextField()),
                ("postal_code", models.CharField(max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_shipments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipments",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipment",
                "verbose_name_plural": "Shipments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_status", models.CharField(blank=True, max_length=30)),
                ("new_status", models.CharField(max_length=30)),
                ("message", models.TextField(blank=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipment_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="shipping.shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipment Event",
                "verbose_name_plural": "Shipment Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["shipment_number"], name="shipping_sh_shipmen_33cb73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["order", "-created_at"], name="shipping_sh_order_i_a287c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["user", "-created_at"], name="shipping_sh_user_id_970bf4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["carrier"], name="shipping_sh_carrier_4e959d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(fields=["status"], name="shipping_sh_status_0644c6_idx"),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["tracking_number"], name="shipping_sh_trackin_af3d4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["-created_at"], name="shipping_sh_created_ee9943_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="shipment",
            constraint=models.CheckConstraint(
                condition=models.Q(("shipping_cost__gte", 0)),
                name="shipment_shipping_cost_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="shipmentevent",
            index=models.Index(
                fields=["shipment", "-created_at"],
                name="shipping_sh_shipmen_d11d1e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shipmentevent",
            index=models.Index(
                fields=["new_status"], name="shipping_sh_new_sta_b121b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipmentevent",
            index=models.Index(
                fields=["-created_at"], name="shipping_sh_created_21760a_idx"
            ),
        ),
    ]
