# Generated by Django 5.2.12 on 2026-06-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0002_adminlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("assign_role", "Assign Role"),
                    ("remove_role", "Remove Role"),
                    ("approve_seller", "Approve Seller"),
                    ("reject_seller", "Reject Seller"),
                    ("suspend_user", "Suspend User"),
                    ("activate_user", "Activate User"),
                    ("change_permission", "Change Permission"),
                    ("create_role", "Create Role"),
                    ("delete_role", "Delete Role"),
                    ("delete_user", "Delete User"),
                    ("update_role", "Update Role"),
                ],
                max_length=50,
            ),
        ),
    ]
