# Generated by Django 5.2.12 on 2026-08-05 01:40

import apps.analytics.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsReportSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "report_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Example: ['sales', 'orders', 'payments']",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("yesterday", "Yesterday"),
                            ("last_7_days", "Last 7 Days"),
                            ("last_30_days", "Last 30 Days"),
                            ("this_month", "This Month"),
                            ("previous_month", "Previous Month"),
                            ("all", "All Time"),
                        ],
                        db_index=True,
                        default="yesterday",
                        max_length=30,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("every_n_days", "Every N Days"),
                        ],
                        db_index=True,
                        default="daily",
                        max_length=30,
                    ),
                ),
                (
                    "time_of_day",
                    models.TimeField(
                        default="02:00",
                        help_text="Time of day when the report should be generated.",
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="0=Monday, 6=Sunday. Used for weekly schedules.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Used for monthly schedules.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "every_n_days",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Used when frequency is every_n_days.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(365),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "next_run_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_analytics_report_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics Report Schedule",
                "verbose_name_plural": "Analytics Report Schedules",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsGeneratedReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("sales", "Sales"),
                            ("orders", "Orders"),
                            ("payments", "Payments"),
                            ("products", "Products"),
                            ("support", "Support"),
                            ("returns", "Returns"),
                            ("reviews", "Reviews"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("yesterday", "Yesterday"),
                            ("last_7_days", "Last 7 Days"),
                            ("last_30_days", "Last 30 Days"),
                            ("this_month", "This Month"),
                            ("previous_month", "Previous Month"),
                            ("all", "All Time"),
                        ],
                        db_index=True,
                        default="yesterday",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.analytics.models.analytics_report_upload_path,
                    ),
                ),
                ("filename", models.CharField(blank=True, max_length=255)),
                ("rows_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("task_id", models.CharField(blank=True, max_length=255)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_analytics_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to="analytics.analyticsreportschedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics Generated Report",
                "verbose_name_plural": "Analytics Generated Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="analyticsreportschedule",
            index=models.Index(
                fields=["is_active", "next_run_at"],
                name="analytics_a_is_acti_57bbe7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsreportschedule",
            index=models.Index(
                fields=["frequency"], name="analytics_a_frequen_b16844_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsreportschedule",
            index=models.Index(fields=["period"], name="analytics_a_period_1f1054_idx"),
        ),
        migrations.AddIndex(
            model_name="analyticsgeneratedreport",
            index=models.Index(fields=["status"], name="analytics_a_status_48781d_idx"),
        ),
        migrations.AddIndex(
            model_name="analyticsgeneratedreport",
            index=models.Index(
                fields=["report_type"], name="analytics_a_report__79a202_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsgeneratedreport",
            index=models.Index(fields=["period"], name="analytics_a_period_d8e15b_idx"),
        ),
        migrations.AddIndex(
            model_name="analyticsgeneratedreport",
            index=models.Index(
                fields=["-created_at"], name="analytics_a_created_8a03f7_idx"
            ),
        ),
    ]
