# Generated by Django 5.2.12 on 2026-07-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("order", "Order"),
                    ("payment", "Payment"),
                    ("shipping", "Shipping"),
                    ("return", "Return"),
                    ("discount", "Discount"),
                    ("system", "System"),
                    ("product", "Product"),
                    ("inventory", "Inventory"),
                ],
                db_index=True,
                default="system",
                max_length=30,
            ),
        ),
    ]
